name: Build

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        name: Checkout
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: yarn build

      - name: Rename the build
        run: mv build client

      - name: Zip the build
        run: zip -r client.zip client/

      - name: Create a release
        uses: ncipollo/release-action@v1
        with:
          artifacts: client.zip
          token: ${{ secrets.GITHUB_TOKEN }}
