name: Build

# Controls when the action will run. Triggers the workflow on pushes to rc branch.
on:
  push:
    branches: "rc"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install
      - run: yarn build
        
      - name: Rename the build
        run: mv build client
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          path: client  
          
      
        
