# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Storybook

on:
  push:
    branches: [ devel ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Build storybook
        run: |
          yarn --frozen-lockfile --silent
          yarn build:css
          yarn build-storybook
      
      - name: Deploy storybook
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: storybook-static
          clean: true
