# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout
      
    - uses: borales/actions-yarn@v2.0.0
      name: yarn install
      with:
        cmd: install
        
    - uses: borales/actions-yarn@v2.0.0
      name: yarn test
      with:
        cmd: test
        
    - uses: borales/actions-yarn@v2.0.0
      name: yarn build
      with:
        cmd: build
        
    - uses: actions/upload-artifact@v2
      name: Upload build artifact
      with:
        name: client
        path: build
            
