name: Build and release

# Controls when the action will run. Triggers the workflow on tag pushes.
on:
  push:
    tags:
      - "*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: borales/actions-yarn@v2.0.0
        name: yarn install
        with:
          cmd: install
      
      - uses: borales/actions-yarn@v2.0.0
        name: yarn build
        with:
          cmd: build
        
      - name: Rename the build
        run: mv build client
        
      - name: Archive and compress
        run: tar -czvf client.tar.gz build
          
      - uses: ncipollo/release-action@v1
        name: Create Github Release
        with:
          artifacts: "client.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
          
      
        
